---
- name: playbook inventory.yaml
  hosts: all
  tasks:
    - name: generation fichier inventory.yaml
      script: convert.sh
    
    - name: config git 
      shell:
        cmd: git config --global user.name "ab-morfik" && git config --global user.email morfikabderrahim@gmail.com       

    - name: Cloner le dépôt Git si ce n'est pas déjà fait
      git:
        repo: 'git@github.com:ab-morfik/inv.git'
        dest: '/var/lib/awx/projects/inv/'
        version: 'main'  # Branche que tu souhaites utiliser
        update: yes

    - name: Ajouter le fichier au dépôt Git local
      ansible.builtin.command:
        cmd: git add inventory.yaml
        #chdir: inv/  # Répertoire local du dépôt Git

    - name: Faire un commit dans le dépôt Git local
      ansible.builtin.command:
        cmd: git commit -m "Mise a jour du fichier inventaire" inventory.yaml
        #chdir: inv/  # Répertoire local du dépôt Git
      ignore_errors: yes

    - name: Pousser les modifications vers le dépôt distant
      ansible.builtin.command:
        cmd: git push -u origin main
        #chdir: inv/      

